name: RealtimeTranslator
options:
  bundleIdPrefix: com.yergakon
targets:
  RealtimeTranslator:
    type: application
    platform: iOS
    deploymentTarget: "18.0"
    sources:
      - path: RealtimeTranslator
    settings:
      INFOPLIST_FILE: RealtimeTranslator/Info.plist
      PRODUCT_BUNDLE_IDENTIFIER: com.yergakon.RealtimeTranslator
  RealtimeTranslatorTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "18.0"
    sources: [RealtimeTranslatorTests]
    dependencies:
      - target: RealtimeTranslator
