name: RealtimeTranslator
options:
  bundleIdPrefix: com.yergakon
packages:
  WebRTC:
    url: https://github.com/webrtc-sdk/WebRTC.git
    from: 125.0.0
targets:
  RealtimeTranslator:
    type: application
    platform: iOS
    deploymentTarget: "18.0"
    sources:
      - path: RealtimeTranslator
    settings:
      INFOPLIST_FILE: RealtimeTranslator/Info.plist
      PRODUCT_BUNDLE_IDENTIFIER: com.yergakon.RealtimeTranslator
    dependencies:
      - package: WebRTC
